# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/nbdev-test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.classifer': { 'nbdev_test.classifer.CatOrDogImageClassifier': ( 'workflow.html#catordogimageclassifier',
                                                                                        'nbdev_test/classifer.py'),
                                      'nbdev_test.classifer.CatOrDogImageClassifier.__init__': ( 'workflow.html#catordogimageclassifier.__init__',
                                                                                                 'nbdev_test/classifer.py'),
                                      'nbdev_test.classifer.CatOrDogImageClassifier.predict': ( 'workflow.html#catordogimageclassifier.predict',
                                                                                                'nbdev_test/classifer.py')},
            'nbdev_test.core': {'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')}}}
