name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        run: |
          mkdir -p ~/.ssh
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SCW_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SCW_SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_ed25519
        
      - name: Test SSH connection
        run: ssh root@51.158.123.189 "echo Connected!"