name: Generate nbdev Docs

on:
  push:
    branches:
      - main  # or your main development branch

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Adjust based on your project's Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyterlab
          pip install nbdev
          nbdev_install_quarto
          pip install jupyterlab-quarto

      # Step 4: Generate documentation
      - name: Generate documentation
        run: |
          pip install -e ".[dev]"
          nbdev_docs

      # Step 5: Checkout or create the docs branch
      - name: Checkout docs branch
        run: |
          # Create a new branch or check out the existing one
          git checkout -b docs || git checkout docs
          
          # Remove everything else from the current branch
          git rm -rf .

          # Copy all files from _docs to the root folder
          cp -r _docs/* ./

      # Step 6: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 7: Commit and push changes
      - name: Commit and push changes
        run: |
          git add .
          # Check if there are any changes
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update API documentation [skip ci]"
            git push origin docs  # Push changes to the docs branch
          fi
